// よく使われているコーディング用の配色を、テーマとして用意したもの。
//
// 値は各テーマの公開パレットから取っている。役割への割り当て（どの色を面に使い、
// どれを文字に使うか）はこちらの判断なので、好みに合わなければ設定画面の
// 「複製して色を編集」で直せる。追加の仕方は theme-authoring.md。
//
// surfaceDeepest は「へこんだ面」で、明暗どちらのテーマでも地（surface）より暗い。
// 入力欄の凹みやリストの地がこれにあたる。
using System.Collections.Generic;

namespace YozoLab.EditorTheme
{
    internal static class PresetThemes
    {
        /// <summary>組み込みのテーマ。先頭が既定。</summary>
        public static IEnumerable<ThemeDefinition> All()
        {
            return new[]
            {
                IcebergDark(),
                IcebergLight(),
            Preset0(),
            Preset1(),
            Preset2(),
            Preset3(),
            Preset4(),
            Preset5(),
            Preset6(),
            Preset7(),
            Preset8(),
            Preset9(),
            };
        }

        /// <summary>テーマが 1 つも決まらないときに使う既定。</summary>
        public static ThemeDefinition Default() => IcebergDark();

        private static ThemeDefinition IcebergDark() => new ThemeDefinition
        {
            name = "Iceberg Dark",
            isDark = true,
            accent = "#84a0c6",
            accentBright = "#91acd1",
            control = "#3d425b",
            controlBright = "#444b71",
            controlBrightest = "#5b6389",
            error = "#e27878",
            errorBright = "#e98989",
            info = "#89b8c2",
            infoBright = "#95c4ce",
            purple = "#a093c7",
            selection = "#2a3158",
            success = "#b4be82",
            surface = "#161821",
            surfaceDeepest = "#0f1117",
            surfaceHover = "#272c42",
            surfaceRaised = "#1e2132",
            text = "#c6c8d1",
            textBright = "#d2d4de",
            textBrightest = "#eff0f4",
            textDim = "#818596",
            textMuted = "#9a9ca5",
            warning = "#e2a478",
            warningBright = "#e9b189",
            controlSurface = "#3d425b",
            controlSurfaceSelected = "#5b6389",
            textFaint = "#6b7089",
        };

        private static ThemeDefinition IcebergLight() => new ThemeDefinition
        {
            name = "Iceberg Light",
            isDark = false,
            accent = "#2d539e",
            accentBright = "#4f6ca8",
            control = "#757ca3",
            controlBright = "#9fa7bd",
            controlBrightest = "#8b98b6",
            error = "#cc517a",
            errorBright = "#d96f92",
            info = "#3f83a6",
            infoBright = "#5f9ab7",
            purple = "#7759b4",
            selection = "#a7b2cd",
            success = "#668e3d",
            surface = "#e8e9ec",
            surfaceDeepest = "#cad0de",
            surfaceHover = "#c9cdd7",
            surfaceRaised = "#dcdfe7",
            text = "#33374c",
            textBright = "#33374c",
            textBrightest = "#e8e9ec",
            textDim = "#8389a3",
            textMuted = "#6b7089",
            warning = "#c57339",
            warningBright = "#d18a55",
            controlSurface = "#cad0de",
            controlSurfaceSelected = "#a7b2cd",
            textFaint = "#8389a3",
        };

        private static ThemeDefinition Preset0() => new ThemeDefinition
        {
            name = "Dracula",
            isDark = true,
            accent = "#bd93f9",
            accentBright = "#d6b3ff",
            control = "#44475a",
            controlBright = "#6272a4",
            controlBrightest = "#7b86b8",
            error = "#ff5555",
            errorBright = "#ff7b7b",
            info = "#8be9fd",
            infoBright = "#a4efff",
            purple = "#ff79c6",
            selection = "#44475a",
            success = "#50fa7b",
            surface = "#282a36",
            surfaceDeepest = "#191a21",
            surfaceHover = "#424450",
            surfaceRaised = "#343746",
            text = "#f8f8f2",
            textBright = "#ffffff",
            textBrightest = "#ffffff",
            textDim = "#8a92b2",
            textMuted = "#bcc0d0",
            warning = "#ffb86c",
            warningBright = "#ffcd94",
            controlSurface = "#343746",
            controlSurfaceSelected = "#44475a",
            textFaint = "#6272a4",
        };

        private static ThemeDefinition Preset1() => new ThemeDefinition
        {
            name = "Nord",
            isDark = true,
            accent = "#81a1c1",
            accentBright = "#88c0d0",
            control = "#3b4252",
            controlBright = "#4c566a",
            controlBrightest = "#616e88",
            error = "#bf616a",
            errorBright = "#cf7982",
            info = "#8fbcbb",
            infoBright = "#a3cecd",
            purple = "#b48ead",
            selection = "#4c566a",
            success = "#a3be8c",
            surface = "#2e3440",
            surfaceDeepest = "#272c36",
            surfaceHover = "#434c5e",
            surfaceRaised = "#3b4252",
            text = "#d8dee9",
            textBright = "#e5e9f0",
            textBrightest = "#eceff4",
            textDim = "#7b88a1",
            textMuted = "#b8c1d1",
            warning = "#d08770",
            warningBright = "#dda58f",
            controlSurface = "#3b4252",
            controlSurfaceSelected = "#4c566a",
            textFaint = "#616e88",
        };

        private static ThemeDefinition Preset2() => new ThemeDefinition
        {
            name = "Gruvbox Dark",
            isDark = true,
            accent = "#83a598",
            accentBright = "#8ec07c",
            control = "#3c3836",
            controlBright = "#504945",
            controlBrightest = "#665c54",
            error = "#fb4934",
            errorBright = "#ff6b5a",
            info = "#8ec07c",
            infoBright = "#a9d5a0",
            purple = "#d3869b",
            selection = "#504945",
            success = "#b8bb26",
            surface = "#282828",
            surfaceDeepest = "#1d2021",
            surfaceHover = "#3c3836",
            surfaceRaised = "#32302f",
            text = "#ebdbb2",
            textBright = "#fbf1c7",
            textBrightest = "#fbf1c7",
            textDim = "#928374",
            textMuted = "#bdae93",
            warning = "#fe8019",
            warningBright = "#fabd2f",
            controlSurface = "#3c3836",
            controlSurfaceSelected = "#504945",
            textFaint = "#7c6f64",
        };

        private static ThemeDefinition Preset3() => new ThemeDefinition
        {
            name = "Gruvbox Light",
            isDark = false,
            accent = "#076678",
            accentBright = "#458588",
            control = "#ebdbb2",
            controlBright = "#bdae93",
            controlBrightest = "#a89984",
            error = "#9d0006",
            errorBright = "#cc241d",
            info = "#427b58",
            infoBright = "#689d6a",
            purple = "#8f3f71",
            selection = "#d5c4a1",
            success = "#79740e",
            surface = "#fbf1c7",
            surfaceDeepest = "#d5c4a1",
            surfaceHover = "#ebdbb2",
            surfaceRaised = "#f2e5bc",
            text = "#3c3836",
            textBright = "#282828",
            textBrightest = "#fbf1c7",
            textDim = "#7c6f64",
            textMuted = "#665c54",
            warning = "#af3a03",
            warningBright = "#d65d0e",
            controlSurface = "#ebdbb2",
            controlSurfaceSelected = "#d5c4a1",
            textFaint = "#a89984",
        };

        private static ThemeDefinition Preset4() => new ThemeDefinition
        {
            name = "Solarized Dark",
            isDark = true,
            accent = "#268bd2",
            accentBright = "#2aa198",
            control = "#073642",
            controlBright = "#586e75",
            controlBrightest = "#657b83",
            error = "#dc322f",
            errorBright = "#cb4b16",
            info = "#2aa198",
            infoBright = "#4fc3b5",
            purple = "#6c71c4",
            selection = "#586e75",
            success = "#859900",
            surface = "#002b36",
            surfaceDeepest = "#002029",
            surfaceHover = "#0b4451",
            surfaceRaised = "#073642",
            text = "#93a1a1",
            textBright = "#eee8d5",
            textBrightest = "#fdf6e3",
            textDim = "#657b83",
            textMuted = "#839496",
            warning = "#b58900",
            warningBright = "#cb9a00",
            controlSurface = "#073642",
            controlSurfaceSelected = "#586e75",
            textFaint = "#586e75",
        };

        private static ThemeDefinition Preset5() => new ThemeDefinition
        {
            name = "Solarized Light",
            isDark = false,
            accent = "#268bd2",
            accentBright = "#2aa198",
            control = "#eee8d5",
            controlBright = "#93a1a1",
            controlBrightest = "#839496",
            error = "#dc322f",
            errorBright = "#cb4b16",
            info = "#2aa198",
            infoBright = "#268bd2",
            purple = "#6c71c4",
            selection = "#d3cbb7",
            success = "#859900",
            surface = "#fdf6e3",
            surfaceDeepest = "#eee8d5",
            surfaceHover = "#eee8d5",
            surfaceRaised = "#f5efdc",
            text = "#586e75",
            textBright = "#073642",
            textBrightest = "#fdf6e3",
            textDim = "#839496",
            textMuted = "#657b83",
            warning = "#b58900",
            warningBright = "#cb4b16",
            controlSurface = "#eee8d5",
            controlSurfaceSelected = "#d3cbb7",
            textFaint = "#93a1a1",
        };

        private static ThemeDefinition Preset6() => new ThemeDefinition
        {
            name = "Tokyo Night",
            isDark = true,
            accent = "#7aa2f7",
            accentBright = "#9eb9ff",
            control = "#292e42",
            controlBright = "#3b4261",
            controlBrightest = "#414868",
            error = "#f7768e",
            errorBright = "#ff92a6",
            info = "#7dcfff",
            infoBright = "#a0dcff",
            purple = "#bb9af7",
            selection = "#364a82",
            success = "#9ece6a",
            surface = "#1a1b26",
            surfaceDeepest = "#16161e",
            surfaceHover = "#292e42",
            surfaceRaised = "#24283b",
            text = "#c0caf5",
            textBright = "#d5dbf5",
            textBrightest = "#e6eaff",
            textDim = "#737aa2",
            textMuted = "#a9b1d6",
            warning = "#ff9e64",
            warningBright = "#e0af68",
            controlSurface = "#24283b",
            controlSurfaceSelected = "#364a82",
            textFaint = "#565f89",
        };

        private static ThemeDefinition Preset7() => new ThemeDefinition
        {
            name = "Catppuccin Mocha",
            isDark = true,
            accent = "#89b4fa",
            accentBright = "#b4befe",
            control = "#313244",
            controlBright = "#45475a",
            controlBrightest = "#585b70",
            error = "#f38ba8",
            errorBright = "#f5a3bb",
            info = "#74c7ec",
            infoBright = "#89dceb",
            purple = "#cba6f7",
            selection = "#585b70",
            success = "#a6e3a1",
            surface = "#1e1e2e",
            surfaceDeepest = "#181825",
            surfaceHover = "#45475a",
            surfaceRaised = "#313244",
            text = "#cdd6f4",
            textBright = "#dce0f5",
            textBrightest = "#f5f5ff",
            textDim = "#9399b2",
            textMuted = "#a6adc8",
            warning = "#fab387",
            warningBright = "#f9e2af",
            controlSurface = "#313244",
            controlSurfaceSelected = "#585b70",
            textFaint = "#6c7086",
        };

        private static ThemeDefinition Preset8() => new ThemeDefinition
        {
            name = "One Dark",
            isDark = true,
            accent = "#61afef",
            accentBright = "#8ac7f5",
            control = "#3a3f4b",
            controlBright = "#4b5263",
            controlBrightest = "#5c6370",
            error = "#e06c75",
            errorBright = "#ea8b93",
            info = "#56b6c2",
            infoBright = "#7fd0da",
            purple = "#c678dd",
            selection = "#3e4451",
            success = "#98c379",
            surface = "#282c34",
            surfaceDeepest = "#21252b",
            surfaceHover = "#3a3f4b",
            surfaceRaised = "#2f343f",
            text = "#abb2bf",
            textBright = "#dcdfe4",
            textBrightest = "#ffffff",
            textDim = "#7f848e",
            textMuted = "#9da5b4",
            warning = "#d19a66",
            warningBright = "#e5c07b",
            controlSurface = "#2f343f",
            controlSurfaceSelected = "#3e4451",
            textFaint = "#5c6370",
        };

        private static ThemeDefinition Preset9() => new ThemeDefinition
        {
            name = "Monokai",
            isDark = true,
            accent = "#66d9ef",
            accentBright = "#a1efff",
            control = "#3e3d32",
            controlBright = "#49483e",
            controlBrightest = "#75715e",
            error = "#f92672",
            errorBright = "#fd5f8f",
            info = "#66d9ef",
            infoBright = "#a1efff",
            purple = "#ae81ff",
            selection = "#49483e",
            success = "#a6e22e",
            surface = "#272822",
            surfaceDeepest = "#1e1f1c",
            surfaceHover = "#3e3d32",
            surfaceRaised = "#2f302a",
            text = "#f8f8f2",
            textBright = "#ffffff",
            textBrightest = "#ffffff",
            textDim = "#908d78",
            textMuted = "#cfcfc2",
            warning = "#fd971f",
            warningBright = "#e6db74",
            controlSurface = "#3e3d32",
            controlSurfaceSelected = "#49483e",
            textFaint = "#75715e",
        };
    }
}
